/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;  
import java.sql.Statement;  
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeFunction.function;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author saran
 */
public class return_books extends javax.swing.JFrame {
  
    Connection con;
   PreparedStatement pst;
   ResultSet rs;
    Statement statement;
    private String sql;
    String query;
     SimpleDateFormat format=new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form return_books
     */
    public return_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aun = new javax.swing.JTextField();
        stuname = new javax.swing.JTextField();
        regno = new javax.swing.JTextField();
        bkacc = new javax.swing.JTextField();
        bkn = new javax.swing.JTextField();
        cale = new com.toedter.calendar.JDateChooser();
        select = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        retn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("RETURN DATE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 220, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("STUDENT NAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("REG.NO");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 220, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("BOOK ACCESS NO");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("BOOK NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 220, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("AUTHOR NAME");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 220, 40));

        aun.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        aun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        aun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aunActionPerformed(evt);
            }
        });
        jPanel1.add(aun, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 220, 30));

        stuname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        stuname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        stuname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                stunameInputMethodTextChanged(evt);
            }
        });
        stuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunameActionPerformed(evt);
            }
        });
        jPanel1.add(stuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 220, 30));

        regno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        regno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        jPanel1.add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        bkacc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bkacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        bkacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkaccActionPerformed(evt);
            }
        });
        jPanel1.add(bkacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 220, 30));

        bkn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bkn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        bkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bknActionPerformed(evt);
            }
        });
        jPanel1.add(bkn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 220, 30));
        jPanel1.add(cale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 220, 40));

        select.setBackground(new java.awt.Color(0, 153, 153));
        select.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 170, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("VIEW  BOOKS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 220, 50));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setText("VIEW ISSUED BOOKS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 50));

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setText("VIEW RETURN BOOKS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 300, 720));

        retn.setBackground(new java.awt.Color(0, 153, 153));
        retn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        retn.setText("RETURN BOOK");
        retn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retnActionPerformed(evt);
            }
        });
        jPanel1.add(retn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aunActionPerformed

    private void stunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameActionPerformed

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void bkaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkaccActionPerformed

    private void bknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bknActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bknActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
         try {  
        Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
         con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "12345");  
        Statement statement = con.createStatement(); 
        pst=con.prepareStatement("select booktittle,author from books where acc_no=? ");
       int r=Integer.parseInt(  bkacc.getText());
       pst.setInt(1,r);
       ResultSet rs1=pst.executeQuery( );
       if(rs1.next()==false)
       {
           JOptionPane.showMessageDialog(this, "Book Not Found");
       }
      else
      bkn.setText (rs1.getString("booktittle"));
       aun.setText (rs1.getString("author"));
    
     
    }                                      
    catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    }  
    }//GEN-LAST:event_selectActionPerformed

    private void retnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retnActionPerformed
        // TODO add your handling code here:
           try {  
               
        Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dat = sdf.format(cale.getDate());
        
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "12345");  
        Statement statement = con.createStatement();  
       statement.executeUpdate("INSERT INTO returnbooks(name,reg,accessno,bookname,author,returneddate) values('"+stuname.getText()+"','"+regno.getText()+"','"+bkacc.getText()+"','"+bkn.getText()+"','"+aun.getText()+"',"+
                                                    "\'" + dat+ "\'" + ")");
         statement.execute("UPDATE books SET status = " + "\"" + "Available" + "\"" + " WHERE acc_no="+ bkacc.getText()+""); 
        JOptionPane.showMessageDialog(null, "Record inserted...");  
        statement.close();  
        con.close();  
        
    } catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    }  
    }//GEN-LAST:event_retnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("Book List"); 
                    try {
                     Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "12345");  
        Statement statement = con.createStatement();  
                String sql="select * from books";
                     ResultSet rs=statement.executeQuery(sql);
                    JTable student_list= new JTable();
                    student_list.setModel(DbUtils.resultSetToTableModel(rs)); 
                    //mention scroll bar
                    JScrollPane scrollPane = new JScrollPane(student_list);
 
                    f.add(scrollPane); //add scrollpane
                    f.setSize(800, 400); //set size for frame
                    f.setVisible(true);
                    f.setLocationRelativeTo(null);
                } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                     JOptionPane.showMessageDialog(null, e1);
                } catch (ClassNotFoundException ex) {       
           Logger.getLogger(studentfun.class.getName()).log(Level.SEVERE, null, ex);
       }       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFrame f = new JFrame(" Issued Book List"); 
                    try {
                     Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "12345");  
        Statement statement = con.createStatement();  
                String sql="select * from issuebooks";
                     ResultSet rs=statement.executeQuery(sql);
                    JTable student_list= new JTable();
                    student_list.setModel(DbUtils.resultSetToTableModel(rs)); 
                    //mention scroll bar
                    JScrollPane scrollPane = new JScrollPane(student_list);
 
                    f.add(scrollPane); //add scrollpane
                    f.setSize(800, 400); //set size for frame
                    f.setVisible(true);
                    f.setLocationRelativeTo(null);
                } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                     JOptionPane.showMessageDialog(null, e1);
                } catch (ClassNotFoundException ex) {       
           Logger.getLogger(studentfun.class.getName()).log(Level.SEVERE, null, ex);
       }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JFrame f = new JFrame(" Return Book List"); 
                    try {
                     Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "12345");  
        Statement statement = con.createStatement();  
                String sql="select * from returnbooks";
                     ResultSet rs=statement.executeQuery(sql);
                    JTable student_list= new JTable();
                    student_list.setModel(DbUtils.resultSetToTableModel(rs)); 
                    //mention scroll bar
                    JScrollPane scrollPane = new JScrollPane(student_list);
 
                    f.add(scrollPane); //add scrollpane
                    f.setSize(800, 400); //set size for frame
                    f.setVisible(true);
                    f.setLocationRelativeTo(null);
                } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                     JOptionPane.showMessageDialog(null, e1);
                } catch (ClassNotFoundException ex) {       
           Logger.getLogger(studentfun.class.getName()).log(Level.SEVERE, null, ex);
       }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void stunameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_stunameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(return_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(return_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(return_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(return_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new return_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aun;
    private javax.swing.JTextField bkacc;
    private javax.swing.JTextField bkn;
    private com.toedter.calendar.JDateChooser cale;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField regno;
    private javax.swing.JButton retn;
    private javax.swing.JButton select;
    private javax.swing.JTextField stuname;
    // End of variables declaration//GEN-END:variables
}
